### PR TITLE
Getnet content release 2021 08 02

### PR DESCRIPTION
**Pull request by suphib**
Update new Footer

### CODE REVIEW

**Comment by suphib** [comment]
@AliAllomani I forgot to fetch upstream

**Review by AliAllomani — CHANGES_REQUESTED** [review]
@suphib please fix the misspelled words

```
content/privacy-policy-2/index.html:1632:3: "Insitutions" is a misspelling of "Institutions"
content/privacy-policy-2/index.html:1952:4: "anonimously" is a misspelling of "anonymously"
content/privacy-policy-2/index.html:3657:3793: "Insitutions" is a misspelling of "Institutions"
content/privacy-policy-2/index.html:3657:10336: "anonimously" is a misspelling of "anonymously"
```

**Comment by suphib** [comment]
> @suphib please fix the misspelled words
> 
> ```
> content/privacy-policy-2/index.html:1632:3: "Insitutions" is a misspelling of "Institutions"
> content/privacy-policy-2/index.html:1952:4: "anonimously" is a misspelling of "anonymously"
> content/privacy-policy-2/index.html:3657:3793: "Insitutions" is a misspelling of "Institutions"
> content/privacy-policy-2/index.html:3657:10336: "anonimously" is a misspelling of "anonymously"
> ```

fixed

**Comment by suphib** [comment]
> @suphib please fix the misspelled words
> 
> ```
> content/privacy-policy-2/index.html:1632:3: "Insitutions" is a misspelling of "Institutions"
> content/privacy-policy-2/index.html:1952:4: "anonimously" is a misspelling of "anonymously"
> content/privacy-policy-2/index.html:3657:3793: "Insitutions" is a misspelling of "Institutions"
> content/privacy-policy-2/index.html:3657:10336: "anonimously" is a misspelling of "anonymously"
> ```

fixed

**Review by AliAllomani — APPROVED** [review]

**Pull request merged**
